In [3]:
import pandas as pd

df_train = pd.read_csv('/home/ankur/Desktop/ML_DL_Projects/data/cmi-detect-behavior-with-sensor-data/train.csv')
df_train_demographics = pd.read_csv('/home/ankur/Desktop/ML_DL_Projects/data/cmi-detect-behavior-with-sensor-data/train_demographics.csv')
df_test = pd.read_csv('/home/ankur/Desktop/ML_DL_Projects/data/cmi-detect-behavior-with-sensor-data/test.csv')
df_test_demographics = pd.read_csv('/home/ankur/Desktop/ML_DL_Projects/data/cmi-detect-behavior-with-sensor-data/test_demographics.csv')
df_merged_train  = pd.merge(df_train, df_train_demographics, on='subject', how='left')

df_test = pd.read_csv('/home/ankur/Desktop/ML_DL_Projects/data/cmi-detect-behavior-with-sensor-data/test.csv')
df_test_demographics = pd.read_csv('/home/ankur/Desktop/ML_DL_Projects/data/cmi-detect-behavior-with-sensor-data/test_demographics.csv')
merged_test = pd.merge(df_test, df_test_demographics, on='subject', how='left')

In [4]:
merged_test.columns.to_list()

['row_id',
 'sequence_id',
 'sequence_counter',
 'subject',
 'acc_x',
 'acc_y',
 'acc_z',
 'rot_w',
 'rot_x',
 'rot_y',
 'rot_z',
 'thm_1',
 'thm_2',
 'thm_3',
 'thm_4',
 'thm_5',
 'tof_1_v0',
 'tof_1_v1',
 'tof_1_v2',
 'tof_1_v3',
 'tof_1_v4',
 'tof_1_v5',
 'tof_1_v6',
 'tof_1_v7',
 'tof_1_v8',
 'tof_1_v9',
 'tof_1_v10',
 'tof_1_v11',
 'tof_1_v12',
 'tof_1_v13',
 'tof_1_v14',
 'tof_1_v15',
 'tof_1_v16',
 'tof_1_v17',
 'tof_1_v18',
 'tof_1_v19',
 'tof_1_v20',
 'tof_1_v21',
 'tof_1_v22',
 'tof_1_v23',
 'tof_1_v24',
 'tof_1_v25',
 'tof_1_v26',
 'tof_1_v27',
 'tof_1_v28',
 'tof_1_v29',
 'tof_1_v30',
 'tof_1_v31',
 'tof_1_v32',
 'tof_1_v33',
 'tof_1_v34',
 'tof_1_v35',
 'tof_1_v36',
 'tof_1_v37',
 'tof_1_v38',
 'tof_1_v39',
 'tof_1_v40',
 'tof_1_v41',
 'tof_1_v42',
 'tof_1_v43',
 'tof_1_v44',
 'tof_1_v45',
 'tof_1_v46',
 'tof_1_v47',
 'tof_1_v48',
 'tof_1_v49',
 'tof_1_v50',
 'tof_1_v51',
 'tof_1_v52',
 'tof_1_v53',
 'tof_1_v54',
 'tof_1_v55',
 'tof_1_v56',
 'tof_1_v57',
 'tof_1_v58',
 'tof_1_v59',
 'tof_1_v60',
 'tof_1_v61',
 'tof_1_v62',
 'tof_1_v63',
 'tof_2_v0',
 'tof_2_v1',
 'tof_2_v2',
 'tof_2_v3',
 'tof_2_v4',
 'tof_2_v5',
 'tof_2_v6',
 'tof_2_v7',
 'tof_2_v8',
 'tof_2_v9',
 'tof_2_v10',
 'tof_2_v11',
 'tof_2_v12',
 'tof_2_v13',
 'tof_2_v14',
 'tof_2_v15',
 'tof_2_v16',
 'tof_2_v17',
 'tof_2_v18',
 'tof_2_v19',
 'tof_2_v20',
 'tof_2_v21',
 'tof_2_v22',
 'tof_2_v23',
 'tof_2_v24',
 'tof_2_v25',
 'tof_2_v26',
 'tof_2_v27',
 'tof_2_v28',
 'tof_2_v29',
 'tof_2_v30',
 'tof_2_v31',
 'tof_2_v32',
 'tof_2_v33',
 'tof_2_v34',
 'tof_2_v35',
 'tof_2_v36',
 'tof_2_v37',
 'tof_2_v38',
 'tof_2_v39',
 'tof_2_v40',
 'tof_2_v41',
 'tof_2_v42',
 'tof_2_v43',
 'tof_2_v44',
 'tof_2_v45',
 'tof_2_v46',
 'tof_2_v47',
 'tof_2_v48',
 'tof_2_v49',
 'tof_2_v50',
 'tof_2_v51',
 'tof_2_v52',
 'tof_2_v53',
 'tof_2_v54',
 'tof_2_v55',
 'tof_2_v56',
 'tof_2_v57',
 'tof_2_v58',
 'tof_2_v59',
 'tof_2_v60',
 'tof_2_v61',
 'tof_2_v62',
 'tof_2_v63',
 'tof_3_v0',
 'tof_3_v1',
 'tof_3_v2',
 'tof_3_v3',
 'tof_3_v4',
 'tof_3_v5',
 'tof_3_v6',
 'tof_3_v7',
 'tof_3_v8',
 'tof_3_v9',
 'tof_3_v10',
 'tof_3_v11',
 'tof_3_v12',
 'tof_3_v13',
 'tof_3_v14',
 'tof_3_v15',
 'tof_3_v16',
 'tof_3_v17',
 'tof_3_v18',
 'tof_3_v19',
 'tof_3_v20',
 'tof_3_v21',
 'tof_3_v22',
 'tof_3_v23',
 'tof_3_v24',
 'tof_3_v25',
 'tof_3_v26',
 'tof_3_v27',
 'tof_3_v28',
 'tof_3_v29',
 'tof_3_v30',
 'tof_3_v31',
 'tof_3_v32',
 'tof_3_v33',
 'tof_3_v34',
 'tof_3_v35',
 'tof_3_v36',
 'tof_3_v37',
 'tof_3_v38',
 'tof_3_v39',
 'tof_3_v40',
 'tof_3_v41',
 'tof_3_v42',
 'tof_3_v43',
 'tof_3_v44',
 'tof_3_v45',
 'tof_3_v46',
 'tof_3_v47',
 'tof_3_v48',
 'tof_3_v49',
 'tof_3_v50',
 'tof_3_v51',
 'tof_3_v52',
 'tof_3_v53',
 'tof_3_v54',
 'tof_3_v55',
 'tof_3_v56',
 'tof_3_v57',
 'tof_3_v58',
 'tof_3_v59',
 'tof_3_v60',
 'tof_3_v61',
 'tof_3_v62',
 'tof_3_v63',
 'tof_4_v0',
 'tof_4_v1',
 'tof_4_v2',
 'tof_4_v3',
 'tof_4_v4',
 'tof_4_v5',
 'tof_4_v6',
 'tof_4_v7',
 'tof_4_v8',
 'tof_4_v9',
 'tof_4_v10',
 'tof_4_v11',
 'tof_4_v12',
 'tof_4_v13',
 'tof_4_v14',
 'tof_4_v15',
 'tof_4_v16',
 'tof_4_v17',
 'tof_4_v18',
 'tof_4_v19',
 'tof_4_v20',
 'tof_4_v21',
 'tof_4_v22',
 'tof_4_v23',
 'tof_4_v24',
 'tof_4_v25',
 'tof_4_v26',
 'tof_4_v27',
 'tof_4_v28',
 'tof_4_v29',
 'tof_4_v30',
 'tof_4_v31',
 'tof_4_v32',
 'tof_4_v33',
 'tof_4_v34',
 'tof_4_v35',
 'tof_4_v36',
 'tof_4_v37',
 'tof_4_v38',
 'tof_4_v39',
 'tof_4_v40',
 'tof_4_v41',
 'tof_4_v42',
 'tof_4_v43',
 'tof_4_v44',
 'tof_4_v45',
 'tof_4_v46',
 'tof_4_v47',
 'tof_4_v48',
 'tof_4_v49',
 'tof_4_v50',
 'tof_4_v51',
 'tof_4_v52',
 'tof_4_v53',
 'tof_4_v54',
 'tof_4_v55',
 'tof_4_v56',
 'tof_4_v57',
 'tof_4_v58',
 'tof_4_v59',
 'tof_4_v60',
 'tof_4_v61',
 'tof_4_v62',
 'tof_4_v63',
 'tof_5_v0',
 'tof_5_v1',
 'tof_5_v2',
 'tof_5_v3',
 'tof_5_v4',
 'tof_5_v5',
 'tof_5_v6',
 'tof_5_v7',
 'tof_5_v8',
 'tof_5_v9',
 'tof_5_v10',
 'tof_5_v11',
 'tof_5_v12',
 'tof_5_v13',
 'tof_5_v14',
 'tof_5_v15',
 'tof_5_v16',
 'tof_5_v17',
 'tof_5_v18',
 'tof_5_v19',
 'tof_5_v20',
 'tof_5_v21',
 'tof_5_v22',
 'tof_5_v23',
 'tof_5_v24',
 'tof_5_v25',
 'tof_5_v26',
 'tof_5_v27',
 'tof_5_v28',
 'tof_5_v29',
 'tof_5_v30',
 'tof_5_v31',
 'tof_5_v32',
 'tof_5_v33',
 'tof_5_v34',
 'tof_5_v35',
 'tof_5_v36',
 'tof_5_v37',
 'tof_5_v38',
 'tof_5_v39',
 'tof_5_v40',
 'tof_5_v41',
 'tof_5_v42',
 'tof_5_v43',
 'tof_5_v44',
 'tof_5_v45',
 'tof_5_v46',
 'tof_5_v47',
 'tof_5_v48',
 'tof_5_v49',
 'tof_5_v50',
 'tof_5_v51',
 'tof_5_v52',
 'tof_5_v53',
 'tof_5_v54',
 'tof_5_v55',
 'tof_5_v56',
 'tof_5_v57',
 'tof_5_v58',
 'tof_5_v59',
 'tof_5_v60',
 'tof_5_v61',
 'tof_5_v62',
 'tof_5_v63',
 'adult_child',
 'age',
 'sex',
 'handedness',
 'height_cm',
 'shoulder_to_wrist_cm',
 'elbow_to_wrist_cm']

In [5]:
merged_test.head()

,row_id,sequence_id,sequence_counter,subject,acc_x,acc_y,acc_z,rot_w,rot_x,rot_y,...,tof_5_v61,tof_5_v62,tof_5_v63,adult_child,age,sex,handedness,height_cm,shoulder_to_wrist_cm,elbow_to_wrist_cm
0,SEQ_000001_000000,SEQ_000001,0,SUBJ_055840,9.039062,5.261719,0.800781,0.367188,-0.397400,-0.629028,...,-1.0,111.0,-1.0,0,13,0,1,177.0,52,27.0
1,SEQ_000001_000001,SEQ_000001,1,SUBJ_055840,9.421875,3.460938,-1.113281,0.353882,-0.507141,-0.652710,...,211.0,187.0,178.0,0,13,0,1,177.0,52,27.0
2,SEQ_000001_000002,SEQ_000001,2,SUBJ_055840,10.160156,2.082031,-3.871094,0.384094,-0.532104,-0.639648,...,-1.0,197.0,177.0,0,13,0,1,177.0,52,27.0
3,SEQ_000001_000003,SEQ_000001,3,SUBJ_055840,9.773438,1.355469,-4.371094,0.387756,-0.531982,-0.634033,...,-1.0,197.0,183.0,0,13,0,1,177.0,52,27.0
4,SEQ_000001_000004,SEQ_000001,4,SUBJ_055840,9.195312,1.011719,-3.222656,0.382751,-0.534180,-0.638367,...,-1.0,200.0,173.0,0,13,0,1,177.0,52,27.0

In [7]:
test = merged_test.drop(columns=['row_id','subject']) 
test.head()

,sequence_id,sequence_counter,acc_x,acc_y,acc_z,rot_w,rot_x,rot_y,rot_z,thm_1,...,tof_5_v61,tof_5_v62,tof_5_v63,adult_child,age,sex,handedness,height_cm,shoulder_to_wrist_cm,elbow_to_wrist_cm
0,SEQ_000001,0,9.039062,5.261719,0.800781,0.367188,-0.397400,-0.629028,-0.558167,30.394640,...,-1.0,111.0,-1.0,0,13,0,1,177.0,52,27.0
1,SEQ_000001,1,9.421875,3.460938,-1.113281,0.353882,-0.507141,-0.652710,-0.437683,30.533144,...,211.0,187.0,178.0,0,13,0,1,177.0,52,27.0
2,SEQ_000001,2,10.160156,2.082031,-3.871094,0.384094,-0.532104,-0.639648,-0.400208,30.971395,...,-1.0,197.0,177.0,0,13,0,1,177.0,52,27.0
3,SEQ_000001,3,9.773438,1.355469,-4.371094,0.387756,-0.531982,-0.634033,-0.405823,31.043678,...,-1.0,197.0,183.0,0,13,0,1,177.0,52,27.0
4,SEQ_000001,4,9.195312,1.011719,-3.222656,0.382751,-0.534180,-0.638367,-0.400818,31.181410,...,-1.0,200.0,173.0,0,13,0,1,177.0,52,27.0

In [8]:
test['sequence_id'].value_counts().max()

np.int64(56)

In [23]:
test = test.sort_values(['sequence_id', 'sequence_counter'], ascending=[True, False])
test.head(6)

,sequence_id,sequence_counter,acc_x,acc_y,acc_z,rot_w,rot_x,rot_y,rot_z,thm_1,...,tof_5_v61,tof_5_v62,tof_5_v63,adult_child,age,sex,handedness,height_cm,shoulder_to_wrist_cm,elbow_to_wrist_cm
55,SEQ_000001,55,7.546875,6.144531,2.410156,0.375854,-0.183777,-0.615234,-0.668152,30.926481,...,166.0,137.0,87.0,0,13,0,1,177.0,52,27.0
54,SEQ_000001,54,9.582031,5.722656,4.093750,0.385193,-0.176208,-0.607788,-0.671692,31.027153,...,163.0,127.0,78.0,0,13,0,1,177.0,52,27.0
53,SEQ_000001,53,6.132812,6.906250,1.796875,0.402466,-0.197510,-0.586182,-0.674866,30.414188,...,-1.0,-1.0,-1.0,0,13,0,1,177.0,52,27.0
52,SEQ_000001,52,6.820312,6.679688,2.679688,0.411316,-0.197754,-0.579956,-0.674805,30.143522,...,-1.0,-1.0,-1.0,0,13,0,1,177.0,52,27.0
51,SEQ_000001,51,6.902344,6.871094,2.488281,0.412720,-0.141357,-0.595032,-0.674988,30.201576,...,-1.0,-1.0,-1.0,0,13,0,1,177.0,52,27.0
50,SEQ_000001,50,6.863281,6.562500,2.945312,0.410950,-0.140198,-0.593140,-0.677979,30.185612,...,167.0,161.0,154.0,0,13,0,1,177.0,52,27.0

In [15]:
test.columns.to_list()

['sequence_id',
 'sequence_counter',
 'acc_x',
 'acc_y',
 'acc_z',
 'rot_w',
 'rot_x',
 'rot_y',
 'rot_z',
 'thm_1',
 'thm_2',
 'thm_3',
 'thm_4',
 'thm_5',
 'tof_1_v0',
 'tof_1_v1',
 'tof_1_v2',
 'tof_1_v3',
 'tof_1_v4',
 'tof_1_v5',
 'tof_1_v6',
 'tof_1_v7',
 'tof_1_v8',
 'tof_1_v9',
 'tof_1_v10',
 'tof_1_v11',
 'tof_1_v12',
 'tof_1_v13',
 'tof_1_v14',
 'tof_1_v15',
 'tof_1_v16',
 'tof_1_v17',
 'tof_1_v18',
 'tof_1_v19',
 'tof_1_v20',
 'tof_1_v21',
 'tof_1_v22',
 'tof_1_v23',
 'tof_1_v24',
 'tof_1_v25',
 'tof_1_v26',
 'tof_1_v27',
 'tof_1_v28',
 'tof_1_v29',
 'tof_1_v30',
 'tof_1_v31',
 'tof_1_v32',
 'tof_1_v33',
 'tof_1_v34',
 'tof_1_v35',
 'tof_1_v36',
 'tof_1_v37',
 'tof_1_v38',
 'tof_1_v39',
 'tof_1_v40',
 'tof_1_v41',
 'tof_1_v42',
 'tof_1_v43',
 'tof_1_v44',
 'tof_1_v45',
 'tof_1_v46',
 'tof_1_v47',
 'tof_1_v48',
 'tof_1_v49',
 'tof_1_v50',
 'tof_1_v51',
 'tof_1_v52',
 'tof_1_v53',
 'tof_1_v54',
 'tof_1_v55',
 'tof_1_v56',
 'tof_1_v57',
 'tof_1_v58',
 'tof_1_v59',
 'tof_1_v60',
 'tof_1_v61',
 'tof_1_v62',
 'tof_1_v63',
 'tof_2_v0',
 'tof_2_v1',
 'tof_2_v2',
 'tof_2_v3',
 'tof_2_v4',
 'tof_2_v5',
 'tof_2_v6',
 'tof_2_v7',
 'tof_2_v8',
 'tof_2_v9',
 'tof_2_v10',
 'tof_2_v11',
 'tof_2_v12',
 'tof_2_v13',
 'tof_2_v14',
 'tof_2_v15',
 'tof_2_v16',
 'tof_2_v17',
 'tof_2_v18',
 'tof_2_v19',
 'tof_2_v20',
 'tof_2_v21',
 'tof_2_v22',
 'tof_2_v23',
 'tof_2_v24',
 'tof_2_v25',
 'tof_2_v26',
 'tof_2_v27',
 'tof_2_v28',
 'tof_2_v29',
 'tof_2_v30',
 'tof_2_v31',
 'tof_2_v32',
 'tof_2_v33',
 'tof_2_v34',
 'tof_2_v35',
 'tof_2_v36',
 'tof_2_v37',
 'tof_2_v38',
 'tof_2_v39',
 'tof_2_v40',
 'tof_2_v41',
 'tof_2_v42',
 'tof_2_v43',
 'tof_2_v44',
 'tof_2_v45',
 'tof_2_v46',
 'tof_2_v47',
 'tof_2_v48',
 'tof_2_v49',
 'tof_2_v50',
 'tof_2_v51',
 'tof_2_v52',
 'tof_2_v53',
 'tof_2_v54',
 'tof_2_v55',
 'tof_2_v56',
 'tof_2_v57',
 'tof_2_v58',
 'tof_2_v59',
 'tof_2_v60',
 'tof_2_v61',
 'tof_2_v62',
 'tof_2_v63',
 'tof_3_v0',
 'tof_3_v1',
 'tof_3_v2',
 'tof_3_v3',
 'tof_3_v4',
 'tof_3_v5',
 'tof_3_v6',
 'tof_3_v7',
 'tof_3_v8',
 'tof_3_v9',
 'tof_3_v10',
 'tof_3_v11',
 'tof_3_v12',
 'tof_3_v13',
 'tof_3_v14',
 'tof_3_v15',
 'tof_3_v16',
 'tof_3_v17',
 'tof_3_v18',
 'tof_3_v19',
 'tof_3_v20',
 'tof_3_v21',
 'tof_3_v22',
 'tof_3_v23',
 'tof_3_v24',
 'tof_3_v25',
 'tof_3_v26',
 'tof_3_v27',
 'tof_3_v28',
 'tof_3_v29',
 'tof_3_v30',
 'tof_3_v31',
 'tof_3_v32',
 'tof_3_v33',
 'tof_3_v34',
 'tof_3_v35',
 'tof_3_v36',
 'tof_3_v37',
 'tof_3_v38',
 'tof_3_v39',
 'tof_3_v40',
 'tof_3_v41',
 'tof_3_v42',
 'tof_3_v43',
 'tof_3_v44',
 'tof_3_v45',
 'tof_3_v46',
 'tof_3_v47',
 'tof_3_v48',
 'tof_3_v49',
 'tof_3_v50',
 'tof_3_v51',
 'tof_3_v52',
 'tof_3_v53',
 'tof_3_v54',
 'tof_3_v55',
 'tof_3_v56',
 'tof_3_v57',
 'tof_3_v58',
 'tof_3_v59',
 'tof_3_v60',
 'tof_3_v61',
 'tof_3_v62',
 'tof_3_v63',
 'tof_4_v0',
 'tof_4_v1',
 'tof_4_v2',
 'tof_4_v3',
 'tof_4_v4',
 'tof_4_v5',
 'tof_4_v6',
 'tof_4_v7',
 'tof_4_v8',
 'tof_4_v9',
 'tof_4_v10',
 'tof_4_v11',
 'tof_4_v12',
 'tof_4_v13',
 'tof_4_v14',
 'tof_4_v15',
 'tof_4_v16',
 'tof_4_v17',
 'tof_4_v18',
 'tof_4_v19',
 'tof_4_v20',
 'tof_4_v21',
 'tof_4_v22',
 'tof_4_v23',
 'tof_4_v24',
 'tof_4_v25',
 'tof_4_v26',
 'tof_4_v27',
 'tof_4_v28',
 'tof_4_v29',
 'tof_4_v30',
 'tof_4_v31',
 'tof_4_v32',
 'tof_4_v33',
 'tof_4_v34',
 'tof_4_v35',
 'tof_4_v36',
 'tof_4_v37',
 'tof_4_v38',
 'tof_4_v39',
 'tof_4_v40',
 'tof_4_v41',
 'tof_4_v42',
 'tof_4_v43',
 'tof_4_v44',
 'tof_4_v45',
 'tof_4_v46',
 'tof_4_v47',
 'tof_4_v48',
 'tof_4_v49',
 'tof_4_v50',
 'tof_4_v51',
 'tof_4_v52',
 'tof_4_v53',
 'tof_4_v54',
 'tof_4_v55',
 'tof_4_v56',
 'tof_4_v57',
 'tof_4_v58',
 'tof_4_v59',
 'tof_4_v60',
 'tof_4_v61',
 'tof_4_v62',
 'tof_4_v63',
 'tof_5_v0',
 'tof_5_v1',
 'tof_5_v2',
 'tof_5_v3',
 'tof_5_v4',
 'tof_5_v5',
 'tof_5_v6',
 'tof_5_v7',
 'tof_5_v8',
 'tof_5_v9',
 'tof_5_v10',
 'tof_5_v11',
 'tof_5_v12',
 'tof_5_v13',
 'tof_5_v14',
 'tof_5_v15',
 'tof_5_v16',
 'tof_5_v17',
 'tof_5_v18',
 'tof_5_v19',
 'tof_5_v20',
 'tof_5_v21',
 'tof_5_v22',
 'tof_5_v23',
 'tof_5_v24',
 'tof_5_v25',
 'tof_5_v26',
 'tof_5_v27',
 'tof_5_v28',
 'tof_5_v29',
 'tof_5_v30',
 'tof_5_v31',
 'tof_5_v32',
 'tof_5_v33',
 'tof_5_v34',
 'tof_5_v35',
 'tof_5_v36',
 'tof_5_v37',
 'tof_5_v38',
 'tof_5_v39',
 'tof_5_v40',
 'tof_5_v41',
 'tof_5_v42',
 'tof_5_v43',
 'tof_5_v44',
 'tof_5_v45',
 'tof_5_v46',
 'tof_5_v47',
 'tof_5_v48',
 'tof_5_v49',
 'tof_5_v50',
 'tof_5_v51',
 'tof_5_v52',
 'tof_5_v53',
 'tof_5_v54',
 'tof_5_v55',
 'tof_5_v56',
 'tof_5_v57',
 'tof_5_v58',
 'tof_5_v59',
 'tof_5_v60',
 'tof_5_v61',
 'tof_5_v62',
 'tof_5_v63',
 'adult_child',
 'age',
 'sex',
 'handedness',
 'height_cm',
 'shoulder_to_wrist_cm',
 'elbow_to_wrist_cm']

In [16]:
#  'age', mean 
#  'sex', mode 
#  'handedness', mode 
#  'height_cm', mean
#  'shoulder_to_wrist_cm', mean
#  'elbow_to_wrist_cm' mean

In [17]:
print("Null values per column:")
print(test.isnull().sum())

Null values per column:
sequence_id             0
sequence_counter        0
acc_x                   0
acc_y                   0
acc_z                   0
                       ..
sex                     0
handedness              0
height_cm               0
shoulder_to_wrist_cm    0
elbow_to_wrist_cm       0
Length: 341, dtype: int64

In [24]:
# Fill null values based on your rules
test['age'] = test['age'].fillna(test['age'].mean())
test['sex'] = test['sex'].fillna(test['sex'].mode()[0])
test['adult_child'] = test['adult_child'].fillna(test['adult_child'].mode()[0])

test['handedness'] = test['handedness'].fillna(test['handedness'].mode()[0])
test['height_cm'] = test['height_cm'].fillna(test['height_cm'].mean())
test['shoulder_to_wrist_cm'] = test['shoulder_to_wrist_cm'].fillna(test['shoulder_to_wrist_cm'].mean())
test['elbow_to_wrist_cm'] = test['elbow_to_wrist_cm'].fillna(test['elbow_to_wrist_cm'].mean())

In [25]:

# Prefixes to check
prefixes = ["acc", "rot", "thm", "tof"]

# Find columns starting with any of the prefixes
matching_cols = [col for col in test.columns if any(col.startswith(p) for p in prefixes)]

# Count them
print("Matching columns:", matching_cols)
print("Number of matching columns:", len(matching_cols))

Matching columns: ['acc_x', 'acc_y', 'acc_z', 'rot_w', 'rot_x', 'rot_y', 'rot_z', 'thm_1', 'thm_2', 'thm_3', 'thm_4', 'thm_5', 'tof_1_v0', 'tof_1_v1', 'tof_1_v2', 'tof_1_v3', 'tof_1_v4', 'tof_1_v5', 'tof_1_v6', 'tof_1_v7', 'tof_1_v8', 'tof_1_v9', 'tof_1_v10', 'tof_1_v11', 'tof_1_v12', 'tof_1_v13', 'tof_1_v14', 'tof_1_v15', 'tof_1_v16', 'tof_1_v17', 'tof_1_v18', 'tof_1_v19', 'tof_1_v20', 'tof_1_v21', 'tof_1_v22', 'tof_1_v23', 'tof_1_v24', 'tof_1_v25', 'tof_1_v26', 'tof_1_v27', 'tof_1_v28', 'tof_1_v29', 'tof_1_v30', 'tof_1_v31', 'tof_1_v32', 'tof_1_v33', 'tof_1_v34', 'tof_1_v35', 'tof_1_v36', 'tof_1_v37', 'tof_1_v38', 'tof_1_v39', 'tof_1_v40', 'tof_1_v41', 'tof_1_v42', 'tof_1_v43', 'tof_1_v44', 'tof_1_v45', 'tof_1_v46', 'tof_1_v47', 'tof_1_v48', 'tof_1_v49', 'tof_1_v50', 'tof_1_v51', 'tof_1_v52', 'tof_1_v53', 'tof_1_v54', 'tof_1_v55', 'tof_1_v56', 'tof_1_v57', 'tof_1_v58', 'tof_1_v59', 'tof_1_v60', 'tof_1_v61', 'tof_1_v62', 'tof_1_v63', 'tof_2_v0', 'tof_2_v1', 'tof_2_v2', 'tof_2_v3', 'tof_2_v4', 'tof_2_v5', 'tof_2_v6', 'tof_2_v7', 'tof_2_v8', 'tof_2_v9', 'tof_2_v10', 'tof_2_v11', 'tof_2_v12', 'tof_2_v13', 'tof_2_v14', 'tof_2_v15', 'tof_2_v16', 'tof_2_v17', 'tof_2_v18', 'tof_2_v19', 'tof_2_v20', 'tof_2_v21', 'tof_2_v22', 'tof_2_v23', 'tof_2_v24', 'tof_2_v25', 'tof_2_v26', 'tof_2_v27', 'tof_2_v28', 'tof_2_v29', 'tof_2_v30', 'tof_2_v31', 'tof_2_v32', 'tof_2_v33', 'tof_2_v34', 'tof_2_v35', 'tof_2_v36', 'tof_2_v37', 'tof_2_v38', 'tof_2_v39', 'tof_2_v40', 'tof_2_v41', 'tof_2_v42', 'tof_2_v43', 'tof_2_v44', 'tof_2_v45', 'tof_2_v46', 'tof_2_v47', 'tof_2_v48', 'tof_2_v49', 'tof_2_v50', 'tof_2_v51', 'tof_2_v52', 'tof_2_v53', 'tof_2_v54', 'tof_2_v55', 'tof_2_v56', 'tof_2_v57', 'tof_2_v58', 'tof_2_v59', 'tof_2_v60', 'tof_2_v61', 'tof_2_v62', 'tof_2_v63', 'tof_3_v0', 'tof_3_v1', 'tof_3_v2', 'tof_3_v3', 'tof_3_v4', 'tof_3_v5', 'tof_3_v6', 'tof_3_v7', 'tof_3_v8', 'tof_3_v9', 'tof_3_v10', 'tof_3_v11', 'tof_3_v12', 'tof_3_v13', 'tof_3_v14', 'tof_3_v15', 'tof_3_v16', 'tof_3_v17', 'tof_3_v18', 'tof_3_v19', 'tof_3_v20', 'tof_3_v21', 'tof_3_v22', 'tof_3_v23', 'tof_3_v24', 'tof_3_v25', 'tof_3_v26', 'tof_3_v27', 'tof_3_v28', 'tof_3_v29', 'tof_3_v30', 'tof_3_v31', 'tof_3_v32', 'tof_3_v33', 'tof_3_v34', 'tof_3_v35', 'tof_3_v36', 'tof_3_v37', 'tof_3_v38', 'tof_3_v39', 'tof_3_v40', 'tof_3_v41', 'tof_3_v42', 'tof_3_v43', 'tof_3_v44', 'tof_3_v45', 'tof_3_v46', 'tof_3_v47', 'tof_3_v48', 'tof_3_v49', 'tof_3_v50', 'tof_3_v51', 'tof_3_v52', 'tof_3_v53', 'tof_3_v54', 'tof_3_v55', 'tof_3_v56', 'tof_3_v57', 'tof_3_v58', 'tof_3_v59', 'tof_3_v60', 'tof_3_v61', 'tof_3_v62', 'tof_3_v63', 'tof_4_v0', 'tof_4_v1', 'tof_4_v2', 'tof_4_v3', 'tof_4_v4', 'tof_4_v5', 'tof_4_v6', 'tof_4_v7', 'tof_4_v8', 'tof_4_v9', 'tof_4_v10', 'tof_4_v11', 'tof_4_v12', 'tof_4_v13', 'tof_4_v14', 'tof_4_v15', 'tof_4_v16', 'tof_4_v17', 'tof_4_v18', 'tof_4_v19', 'tof_4_v20', 'tof_4_v21', 'tof_4_v22', 'tof_4_v23', 'tof_4_v24', 'tof_4_v25', 'tof_4_v26', 'tof_4_v27', 'tof_4_v28', 'tof_4_v29', 'tof_4_v30', 'tof_4_v31', 'tof_4_v32', 'tof_4_v33', 'tof_4_v34', 'tof_4_v35', 'tof_4_v36', 'tof_4_v37', 'tof_4_v38', 'tof_4_v39', 'tof_4_v40', 'tof_4_v41', 'tof_4_v42', 'tof_4_v43', 'tof_4_v44', 'tof_4_v45', 'tof_4_v46', 'tof_4_v47', 'tof_4_v48', 'tof_4_v49', 'tof_4_v50', 'tof_4_v51', 'tof_4_v52', 'tof_4_v53', 'tof_4_v54', 'tof_4_v55', 'tof_4_v56', 'tof_4_v57', 'tof_4_v58', 'tof_4_v59', 'tof_4_v60', 'tof_4_v61', 'tof_4_v62', 'tof_4_v63', 'tof_5_v0', 'tof_5_v1', 'tof_5_v2', 'tof_5_v3', 'tof_5_v4', 'tof_5_v5', 'tof_5_v6', 'tof_5_v7', 'tof_5_v8', 'tof_5_v9', 'tof_5_v10', 'tof_5_v11', 'tof_5_v12', 'tof_5_v13', 'tof_5_v14', 'tof_5_v15', 'tof_5_v16', 'tof_5_v17', 'tof_5_v18', 'tof_5_v19', 'tof_5_v20', 'tof_5_v21', 'tof_5_v22', 'tof_5_v23', 'tof_5_v24', 'tof_5_v25', 'tof_5_v26', 'tof_5_v27', 'tof_5_v28', 'tof_5_v29', 'tof_5_v30', 'tof_5_v31', 'tof_5_v32', 'tof_5_v33', 'tof_5_v34', 'tof_5_v35', 'tof_5_v36', 'tof_5_v37', 'tof_5_v38', 'tof_5_v39', 'tof_5_v40', 'tof_5_v41', 'tof_5_v42', 'tof_5_v43', 'tof_5_v44', 'tof_5_v45', 'tof_5_v46', 'tof_5_v47', 'tof_5_v48', 'tof_5_v49', 'tof_5_v50', 'tof_5_v51', 'tof_5_v52', 'tof_5_v53', 'tof_5_v54', 'tof_5_v55', 'tof_5_v56', 'tof_5_v57', 'tof_5_v58', 'tof_5_v59', 'tof_5_v60', 'tof_5_v61', 'tof_5_v62', 'tof_5_v63']
Number of matching columns: 332

In [29]:

import numpy as np
df = test

# Find target columns
prefixes = ("acc", "rot", "thm", "tof")
target_cols = [col for col in df.columns if col.startswith(prefixes)]

# Fill NaNs
for col in target_cols:
    for idx in df.index[df[col].isna()]:
        prev_val = df[col].iloc[idx-1] if idx > 0 else np.nan
        next_val = df[col].iloc[idx+1] if idx < len(df)-1 else np.nan

        if not np.isnan(prev_val) and not np.isnan(next_val):
            df.loc[idx, col] = (prev_val + next_val) / 2
        elif not np.isnan(prev_val):
            df.loc[idx, col] = prev_val
        elif not np.isnan(next_val):
            df.loc[idx, col] = next_val

test = df

In [30]:
print(test.isnull().sum())

sequence_id             0
sequence_counter        0
acc_x                   0
acc_y                   0
acc_z                   0
                       ..
sex                     0
handedness              0
height_cm               0
shoulder_to_wrist_cm    0
elbow_to_wrist_cm       0
Length: 341, dtype: int64

In [33]:
test.columns.to_list()

['sequence_id',
 'sequence_counter',
 'acc_x',
 'acc_y',
 'acc_z',
 'rot_w',
 'rot_x',
 'rot_y',
 'rot_z',
 'thm_1',
 'thm_2',
 'thm_3',
 'thm_4',
 'thm_5',
 'tof_1_v0',
 'tof_1_v1',
 'tof_1_v2',
 'tof_1_v3',
 'tof_1_v4',
 'tof_1_v5',
 'tof_1_v6',
 'tof_1_v7',
 'tof_1_v8',
 'tof_1_v9',
 'tof_1_v10',
 'tof_1_v11',
 'tof_1_v12',
 'tof_1_v13',
 'tof_1_v14',
 'tof_1_v15',
 'tof_1_v16',
 'tof_1_v17',
 'tof_1_v18',
 'tof_1_v19',
 'tof_1_v20',
 'tof_1_v21',
 'tof_1_v22',
 'tof_1_v23',
 'tof_1_v24',
 'tof_1_v25',
 'tof_1_v26',
 'tof_1_v27',
 'tof_1_v28',
 'tof_1_v29',
 'tof_1_v30',
 'tof_1_v31',
 'tof_1_v32',
 'tof_1_v33',
 'tof_1_v34',
 'tof_1_v35',
 'tof_1_v36',
 'tof_1_v37',
 'tof_1_v38',
 'tof_1_v39',
 'tof_1_v40',
 'tof_1_v41',
 'tof_1_v42',
 'tof_1_v43',
 'tof_1_v44',
 'tof_1_v45',
 'tof_1_v46',
 'tof_1_v47',
 'tof_1_v48',
 'tof_1_v49',
 'tof_1_v50',
 'tof_1_v51',
 'tof_1_v52',
 'tof_1_v53',
 'tof_1_v54',
 'tof_1_v55',
 'tof_1_v56',
 'tof_1_v57',
 'tof_1_v58',
 'tof_1_v59',
 'tof_1_v60',
 'tof_1_v61',
 'tof_1_v62',
 'tof_1_v63',
 'tof_2_v0',
 'tof_2_v1',
 'tof_2_v2',
 'tof_2_v3',
 'tof_2_v4',
 'tof_2_v5',
 'tof_2_v6',
 'tof_2_v7',
 'tof_2_v8',
 'tof_2_v9',
 'tof_2_v10',
 'tof_2_v11',
 'tof_2_v12',
 'tof_2_v13',
 'tof_2_v14',
 'tof_2_v15',
 'tof_2_v16',
 'tof_2_v17',
 'tof_2_v18',
 'tof_2_v19',
 'tof_2_v20',
 'tof_2_v21',
 'tof_2_v22',
 'tof_2_v23',
 'tof_2_v24',
 'tof_2_v25',
 'tof_2_v26',
 'tof_2_v27',
 'tof_2_v28',
 'tof_2_v29',
 'tof_2_v30',
 'tof_2_v31',
 'tof_2_v32',
 'tof_2_v33',
 'tof_2_v34',
 'tof_2_v35',
 'tof_2_v36',
 'tof_2_v37',
 'tof_2_v38',
 'tof_2_v39',
 'tof_2_v40',
 'tof_2_v41',
 'tof_2_v42',
 'tof_2_v43',
 'tof_2_v44',
 'tof_2_v45',
 'tof_2_v46',
 'tof_2_v47',
 'tof_2_v48',
 'tof_2_v49',
 'tof_2_v50',
 'tof_2_v51',
 'tof_2_v52',
 'tof_2_v53',
 'tof_2_v54',
 'tof_2_v55',
 'tof_2_v56',
 'tof_2_v57',
 'tof_2_v58',
 'tof_2_v59',
 'tof_2_v60',
 'tof_2_v61',
 'tof_2_v62',
 'tof_2_v63',
 'tof_3_v0',
 'tof_3_v1',
 'tof_3_v2',
 'tof_3_v3',
 'tof_3_v4',
 'tof_3_v5',
 'tof_3_v6',
 'tof_3_v7',
 'tof_3_v8',
 'tof_3_v9',
 'tof_3_v10',
 'tof_3_v11',
 'tof_3_v12',
 'tof_3_v13',
 'tof_3_v14',
 'tof_3_v15',
 'tof_3_v16',
 'tof_3_v17',
 'tof_3_v18',
 'tof_3_v19',
 'tof_3_v20',
 'tof_3_v21',
 'tof_3_v22',
 'tof_3_v23',
 'tof_3_v24',
 'tof_3_v25',
 'tof_3_v26',
 'tof_3_v27',
 'tof_3_v28',
 'tof_3_v29',
 'tof_3_v30',
 'tof_3_v31',
 'tof_3_v32',
 'tof_3_v33',
 'tof_3_v34',
 'tof_3_v35',
 'tof_3_v36',
 'tof_3_v37',
 'tof_3_v38',
 'tof_3_v39',
 'tof_3_v40',
 'tof_3_v41',
 'tof_3_v42',
 'tof_3_v43',
 'tof_3_v44',
 'tof_3_v45',
 'tof_3_v46',
 'tof_3_v47',
 'tof_3_v48',
 'tof_3_v49',
 'tof_3_v50',
 'tof_3_v51',
 'tof_3_v52',
 'tof_3_v53',
 'tof_3_v54',
 'tof_3_v55',
 'tof_3_v56',
 'tof_3_v57',
 'tof_3_v58',
 'tof_3_v59',
 'tof_3_v60',
 'tof_3_v61',
 'tof_3_v62',
 'tof_3_v63',
 'tof_4_v0',
 'tof_4_v1',
 'tof_4_v2',
 'tof_4_v3',
 'tof_4_v4',
 'tof_4_v5',
 'tof_4_v6',
 'tof_4_v7',
 'tof_4_v8',
 'tof_4_v9',
 'tof_4_v10',
 'tof_4_v11',
 'tof_4_v12',
 'tof_4_v13',
 'tof_4_v14',
 'tof_4_v15',
 'tof_4_v16',
 'tof_4_v17',
 'tof_4_v18',
 'tof_4_v19',
 'tof_4_v20',
 'tof_4_v21',
 'tof_4_v22',
 'tof_4_v23',
 'tof_4_v24',
 'tof_4_v25',
 'tof_4_v26',
 'tof_4_v27',
 'tof_4_v28',
 'tof_4_v29',
 'tof_4_v30',
 'tof_4_v31',
 'tof_4_v32',
 'tof_4_v33',
 'tof_4_v34',
 'tof_4_v35',
 'tof_4_v36',
 'tof_4_v37',
 'tof_4_v38',
 'tof_4_v39',
 'tof_4_v40',
 'tof_4_v41',
 'tof_4_v42',
 'tof_4_v43',
 'tof_4_v44',
 'tof_4_v45',
 'tof_4_v46',
 'tof_4_v47',
 'tof_4_v48',
 'tof_4_v49',
 'tof_4_v50',
 'tof_4_v51',
 'tof_4_v52',
 'tof_4_v53',
 'tof_4_v54',
 'tof_4_v55',
 'tof_4_v56',
 'tof_4_v57',
 'tof_4_v58',
 'tof_4_v59',
 'tof_4_v60',
 'tof_4_v61',
 'tof_4_v62',
 'tof_4_v63',
 'tof_5_v0',
 'tof_5_v1',
 'tof_5_v2',
 'tof_5_v3',
 'tof_5_v4',
 'tof_5_v5',
 'tof_5_v6',
 'tof_5_v7',
 'tof_5_v8',
 'tof_5_v9',
 'tof_5_v10',
 'tof_5_v11',
 'tof_5_v12',
 'tof_5_v13',
 'tof_5_v14',
 'tof_5_v15',
 'tof_5_v16',
 'tof_5_v17',
 'tof_5_v18',
 'tof_5_v19',
 'tof_5_v20',
 'tof_5_v21',
 'tof_5_v22',
 'tof_5_v23',
 'tof_5_v24',
 'tof_5_v25',
 'tof_5_v26',
 'tof_5_v27',
 'tof_5_v28',
 'tof_5_v29',
 'tof_5_v30',
 'tof_5_v31',
 'tof_5_v32',
 'tof_5_v33',
 'tof_5_v34',
 'tof_5_v35',
 'tof_5_v36',
 'tof_5_v37',
 'tof_5_v38',
 'tof_5_v39',
 'tof_5_v40',
 'tof_5_v41',
 'tof_5_v42',
 'tof_5_v43',
 'tof_5_v44',
 'tof_5_v45',
 'tof_5_v46',
 'tof_5_v47',
 'tof_5_v48',
 'tof_5_v49',
 'tof_5_v50',
 'tof_5_v51',
 'tof_5_v52',
 'tof_5_v53',
 'tof_5_v54',
 'tof_5_v55',
 'tof_5_v56',
 'tof_5_v57',
 'tof_5_v58',
 'tof_5_v59',
 'tof_5_v60',
 'tof_5_v61',
 'tof_5_v62',
 'tof_5_v63',
 'adult_child',
 'age',
 'sex',
 'handedness',
 'height_cm',
 'shoulder_to_wrist_cm',
 'elbow_to_wrist_cm']

In [42]:
feature_list_with_seq_id  =test.columns.to_list()

In [36]:
test.shape

(107, 341)

In [37]:
import numpy as np
import pandas as pd

def prepare_sequences(df, max_steps=700):
    # Drop unnecessary columns early
    df = df.sort_values("sequence_counter", ascending=False)
    df = df.drop(columns=["sequence_counter"])  
    
    # Get number of features (exclude seq_id)
    feature_cols = [c for c in df.columns if c != "sequence_id"]
    n_features = len(feature_cols)
    
    # Find number of unique sequences
    sequence_ids = df["sequence_id"].unique()
    n_sequences = len(sequence_ids)

    # Preallocate final array (float32 to save memory)
    X = np.zeros((n_sequences, max_steps, n_features), dtype=np.float32)
    
    for i, seq_id in enumerate(sequence_ids):
        seq = df[df["sequence_id"] == seq_id][feature_cols].values.astype(np.float32)
        
        # Truncate if longer than max_steps, keep first 700
        if len(seq) > max_steps:
            seq = seq[:max_steps]
        
        # Pad if shorter
        X[i, :len(seq), :] = seq
    
    return X

test_1 = prepare_sequences(test)

In [38]:
test_1.shape

(2, 700, 339)

In [39]:
test_1[0,:,:]

array([[  7.546875 ,   6.1445312,   2.4101562, ..., 177.       ,
         52.       ,  27.       ],
       [  9.582031 ,   5.7226562,   4.09375  , ..., 177.       ,
         52.       ,  27.       ],
       [  6.1328125,   6.90625  ,   1.796875 , ..., 177.       ,
         52.       ,  27.       ],
       ...,
       [  0.       ,   0.       ,   0.       , ...,   0.       ,
          0.       ,   0.       ],
       [  0.       ,   0.       ,   0.       , ...,   0.       ,
          0.       ,   0.       ],
       [  0.       ,   0.       ,   0.       , ...,   0.       ,
          0.       ,   0.       ]], dtype=float32)

In [41]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Masking

# ---------------------------
# X.shape = (num_sequences, 700, 339)
# y.shape = (num_sequences, ) or (num_sequences, num_classes)
# ---------------------------

# Example placeholder
# X, y = <your_prepared_data>

num_features = 339
timesteps = 700

# Build LSTM model
model = Sequential([
    # Masking layer helps when sequences are shorter than 700 (if padded with 0s)
    Masking(mask_value=0.0, input_shape=(timesteps, num_features)),

    # LSTM layer (64 units). return_sequences=False means last output only.
    LSTM(64, return_sequences=False),

    Dropout(0.3),   # regularization

    Dense(64, activation="relu"),
    Dense(1, activation="sigmoid")   # for binary classification (adjust for regression/multiclass)
])

# Compile
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",   # change to mse/categorical_crossentropy as needed
    metrics=["accuracy"]
)
y = np.array([0, 1])
# Train
history = model.fit(
    test_1, y,
    batch_size=32,    # adjust to fit GPU memory
    epochs=20,
    validation_split=0.2,
    shuffle=True
)

# Save
history

Epoch 1/20

/home/ankur/Desktop/ML_DL_Projects/ml_projects_venv/lib/python3.12/site-packages/keras/src/layers/core/masking.py:48: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - accuracy: 1.0000 - loss: 0.5005

2025-08-19 11:14:12.554226: E tensorflow/core/util/util.cc:131] oneDNN supports DT_BOOL only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 1.0000 - loss: 0.5005 - val_accuracy: 1.0000 - val_loss: 0.4070
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 1.0000 - loss: 0.1413 - val_accuracy: 1.0000 - val_loss: 0.3912
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 1.0000 - loss: 0.2666 - val_accuracy: 1.0000 - val_loss: 0.3925
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 1.0000 - loss: 0.1195 - val_accuracy: 1.0000 - val_loss: 0.3842
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 1.0000 - loss: 0.1772 - val_accuracy: 1.0000 - val_loss: 0.3829
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 1.0000 - loss: 0.1830 - val_accuracy: 1.0000 - val_loss: 0.3863
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 1.0000 - loss: 0.0929 - val_accuracy: 1.0000 - val_loss: 0.3914
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 1.0000 - loss: 0.0968 - val_accuracy: 1.0000 - val_loss: 0.3969
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - accuracy: 1.0000 - loss: 0.0526 - val_accuracy: 1.0000 - val_loss: 0.4008
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 1.0000 - loss: 0.1225 - val_accuracy: 1.0000 - val_loss: 0.3947
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 1.0000 - loss: 0.0495 - val_accuracy: 1.0000 - val_loss: 0.4002
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 1.0000 - loss: 0.0870 - val_accuracy: 1.0000 - val_loss: 0.4048
Epoch 13/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 1.0000 - loss: 0.0372 - val_accuracy: 1.0000 - val_loss: 0.4092
Epoch 14/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 1.0000 - loss: 0.0693 - val_accuracy: 1.0000 - val_loss: 0.4134
Epoch 15/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 1.0000 - loss: 0.0330 - val_accuracy: 1.0000 - val_loss: 0.4174
Epoch 16/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 1.0000 - loss: 0.0593 - val_accuracy: 1.0000 - val_loss: 0.4210
Epoch 17/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - accuracy: 1.0000 - loss: 0.0498 - val_accuracy: 1.0000 - val_loss: 0.4244
Epoch 18/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 1.0000 - loss: 0.0842 - val_accuracy: 1.0000 - val_loss: 0.4394
Epoch 19/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 1.0000 - loss: 0.0239 - val_accuracy: 1.0000 - val_loss: 0.4420
Epoch 20/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 1.0000 - loss: 0.0271 - val_accuracy: 1.0000 - val_loss: 0.4441

In [44]:
len(feature_list_with_seq_id)

341

In [45]:
df_merged_train.columns.to_list()

['row_id',
 'sequence_type',
 'sequence_id',
 'sequence_counter',
 'subject',
 'orientation',
 'behavior',
 'phase',
 'gesture',
 'acc_x',
 'acc_y',
 'acc_z',
 'rot_w',
 'rot_x',
 'rot_y',
 'rot_z',
 'thm_1',
 'thm_2',
 'thm_3',
 'thm_4',
 'thm_5',
 'tof_1_v0',
 'tof_1_v1',
 'tof_1_v2',
 'tof_1_v3',
 'tof_1_v4',
 'tof_1_v5',
 'tof_1_v6',
 'tof_1_v7',
 'tof_1_v8',
 'tof_1_v9',
 'tof_1_v10',
 'tof_1_v11',
 'tof_1_v12',
 'tof_1_v13',
 'tof_1_v14',
 'tof_1_v15',
 'tof_1_v16',
 'tof_1_v17',
 'tof_1_v18',
 'tof_1_v19',
 'tof_1_v20',
 'tof_1_v21',
 'tof_1_v22',
 'tof_1_v23',
 'tof_1_v24',
 'tof_1_v25',
 'tof_1_v26',
 'tof_1_v27',
 'tof_1_v28',
 'tof_1_v29',
 'tof_1_v30',
 'tof_1_v31',
 'tof_1_v32',
 'tof_1_v33',
 'tof_1_v34',
 'tof_1_v35',
 'tof_1_v36',
 'tof_1_v37',
 'tof_1_v38',
 'tof_1_v39',
 'tof_1_v40',
 'tof_1_v41',
 'tof_1_v42',
 'tof_1_v43',
 'tof_1_v44',
 'tof_1_v45',
 'tof_1_v46',
 'tof_1_v47',
 'tof_1_v48',
 'tof_1_v49',
 'tof_1_v50',
 'tof_1_v51',
 'tof_1_v52',
 'tof_1_v53',
 'tof_1_v54',
 'tof_1_v55',
 'tof_1_v56',
 'tof_1_v57',
 'tof_1_v58',
 'tof_1_v59',
 'tof_1_v60',
 'tof_1_v61',
 'tof_1_v62',
 'tof_1_v63',
 'tof_2_v0',
 'tof_2_v1',
 'tof_2_v2',
 'tof_2_v3',
 'tof_2_v4',
 'tof_2_v5',
 'tof_2_v6',
 'tof_2_v7',
 'tof_2_v8',
 'tof_2_v9',
 'tof_2_v10',
 'tof_2_v11',
 'tof_2_v12',
 'tof_2_v13',
 'tof_2_v14',
 'tof_2_v15',
 'tof_2_v16',
 'tof_2_v17',
 'tof_2_v18',
 'tof_2_v19',
 'tof_2_v20',
 'tof_2_v21',
 'tof_2_v22',
 'tof_2_v23',
 'tof_2_v24',
 'tof_2_v25',
 'tof_2_v26',
 'tof_2_v27',
 'tof_2_v28',
 'tof_2_v29',
 'tof_2_v30',
 'tof_2_v31',
 'tof_2_v32',
 'tof_2_v33',
 'tof_2_v34',
 'tof_2_v35',
 'tof_2_v36',
 'tof_2_v37',
 'tof_2_v38',
 'tof_2_v39',
 'tof_2_v40',
 'tof_2_v41',
 'tof_2_v42',
 'tof_2_v43',
 'tof_2_v44',
 'tof_2_v45',
 'tof_2_v46',
 'tof_2_v47',
 'tof_2_v48',
 'tof_2_v49',
 'tof_2_v50',
 'tof_2_v51',
 'tof_2_v52',
 'tof_2_v53',
 'tof_2_v54',
 'tof_2_v55',
 'tof_2_v56',
 'tof_2_v57',
 'tof_2_v58',
 'tof_2_v59',
 'tof_2_v60',
 'tof_2_v61',
 'tof_2_v62',
 'tof_2_v63',
 'tof_3_v0',
 'tof_3_v1',
 'tof_3_v2',
 'tof_3_v3',
 'tof_3_v4',
 'tof_3_v5',
 'tof_3_v6',
 'tof_3_v7',
 'tof_3_v8',
 'tof_3_v9',
 'tof_3_v10',
 'tof_3_v11',
 'tof_3_v12',
 'tof_3_v13',
 'tof_3_v14',
 'tof_3_v15',
 'tof_3_v16',
 'tof_3_v17',
 'tof_3_v18',
 'tof_3_v19',
 'tof_3_v20',
 'tof_3_v21',
 'tof_3_v22',
 'tof_3_v23',
 'tof_3_v24',
 'tof_3_v25',
 'tof_3_v26',
 'tof_3_v27',
 'tof_3_v28',
 'tof_3_v29',
 'tof_3_v30',
 'tof_3_v31',
 'tof_3_v32',
 'tof_3_v33',
 'tof_3_v34',
 'tof_3_v35',
 'tof_3_v36',
 'tof_3_v37',
 'tof_3_v38',
 'tof_3_v39',
 'tof_3_v40',
 'tof_3_v41',
 'tof_3_v42',
 'tof_3_v43',
 'tof_3_v44',
 'tof_3_v45',
 'tof_3_v46',
 'tof_3_v47',
 'tof_3_v48',
 'tof_3_v49',
 'tof_3_v50',
 'tof_3_v51',
 'tof_3_v52',
 'tof_3_v53',
 'tof_3_v54',
 'tof_3_v55',
 'tof_3_v56',
 'tof_3_v57',
 'tof_3_v58',
 'tof_3_v59',
 'tof_3_v60',
 'tof_3_v61',
 'tof_3_v62',
 'tof_3_v63',
 'tof_4_v0',
 'tof_4_v1',
 'tof_4_v2',
 'tof_4_v3',
 'tof_4_v4',
 'tof_4_v5',
 'tof_4_v6',
 'tof_4_v7',
 'tof_4_v8',
 'tof_4_v9',
 'tof_4_v10',
 'tof_4_v11',
 'tof_4_v12',
 'tof_4_v13',
 'tof_4_v14',
 'tof_4_v15',
 'tof_4_v16',
 'tof_4_v17',
 'tof_4_v18',
 'tof_4_v19',
 'tof_4_v20',
 'tof_4_v21',
 'tof_4_v22',
 'tof_4_v23',
 'tof_4_v24',
 'tof_4_v25',
 'tof_4_v26',
 'tof_4_v27',
 'tof_4_v28',
 'tof_4_v29',
 'tof_4_v30',
 'tof_4_v31',
 'tof_4_v32',
 'tof_4_v33',
 'tof_4_v34',
 'tof_4_v35',
 'tof_4_v36',
 'tof_4_v37',
 'tof_4_v38',
 'tof_4_v39',
 'tof_4_v40',
 'tof_4_v41',
 'tof_4_v42',
 'tof_4_v43',
 'tof_4_v44',
 'tof_4_v45',
 'tof_4_v46',
 'tof_4_v47',
 'tof_4_v48',
 'tof_4_v49',
 'tof_4_v50',
 'tof_4_v51',
 'tof_4_v52',
 'tof_4_v53',
 'tof_4_v54',
 'tof_4_v55',
 'tof_4_v56',
 'tof_4_v57',
 'tof_4_v58',
 'tof_4_v59',
 'tof_4_v60',
 'tof_4_v61',
 'tof_4_v62',
 'tof_4_v63',
 'tof_5_v0',
 'tof_5_v1',
 'tof_5_v2',
 'tof_5_v3',
 'tof_5_v4',
 'tof_5_v5',
 'tof_5_v6',
 'tof_5_v7',
 'tof_5_v8',
 'tof_5_v9',
 'tof_5_v10',
 'tof_5_v11',
 'tof_5_v12',
 'tof_5_v13',
 'tof_5_v14',
 'tof_5_v15',
 'tof_5_v16',
 'tof_5_v17',
 'tof_5_v18',
 'tof_5_v19',
 'tof_5_v20',
 'tof_5_v21',
 'tof_5_v22',
 'tof_5_v23',
 'tof_5_v24',
 'tof_5_v25',
 'tof_5_v26',
 'tof_5_v27',
 'tof_5_v28',
 'tof_5_v29',
 'tof_5_v30',
 'tof_5_v31',
 'tof_5_v32',
 'tof_5_v33',
 'tof_5_v34',
 'tof_5_v35',
 'tof_5_v36',
 'tof_5_v37',
 'tof_5_v38',
 'tof_5_v39',
 'tof_5_v40',
 'tof_5_v41',
 'tof_5_v42',
 'tof_5_v43',
 'tof_5_v44',
 'tof_5_v45',
 'tof_5_v46',
 'tof_5_v47',
 'tof_5_v48',
 'tof_5_v49',
 'tof_5_v50',
 'tof_5_v51',
 'tof_5_v52',
 'tof_5_v53',
 'tof_5_v54',
 'tof_5_v55',
 'tof_5_v56',
 'tof_5_v57',
 'tof_5_v58',
 'tof_5_v59',
 'tof_5_v60',
 'tof_5_v61',
 'tof_5_v62',
 'tof_5_v63',
 'adult_child',
 'age',
 'sex',
 'handedness',
 'height_cm',
 'shoulder_to_wrist_cm',
 'elbow_to_wrist_cm']

In [55]:
df_merged_train["sequence_type"].value_counts()

Series([], Name: count, dtype: int64)

In [53]:
print(df_merged_train["sequence_type"].unique())

[nan]

In [51]:
df_merged_train["sequence_type"] = df_merged_train["sequence_type"].map({
    "Target": 1,
    "Non-Target": 0
})
df_merged_train["sequence_type"].value_counts()

Series([], Name: count, dtype: int64)

In [52]:
df_merged_train.head()

,row_id,sequence_type,sequence_id,sequence_counter,subject,orientation,behavior,phase,gesture,acc_x,...,tof_5_v61,tof_5_v62,tof_5_v63,adult_child,age,sex,handedness,height_cm,shoulder_to_wrist_cm,elbow_to_wrist_cm
0,SEQ_000007_000000,NaN,SEQ_000007,0,SUBJ_059520,Seated Lean Non Dom - FACE DOWN,Relaxes and moves hand to target location,Transition,Cheek - pinch skin,6.683594,...,-1.0,-1.0,-1.0,0,12,1,1,163.0,52,24.0
1,SEQ_000007_000001,NaN,SEQ_000007,1,SUBJ_059520,Seated Lean Non Dom - FACE DOWN,Relaxes and moves hand to target location,Transition,Cheek - pinch skin,6.949219,...,-1.0,-1.0,-1.0,0,12,1,1,163.0,52,24.0
2,SEQ_000007_000002,NaN,SEQ_000007,2,SUBJ_059520,Seated Lean Non Dom - FACE DOWN,Relaxes and moves hand to target location,Transition,Cheek - pinch skin,5.722656,...,-1.0,-1.0,-1.0,0,12,1,1,163.0,52,24.0
3,SEQ_000007_000003,NaN,SEQ_000007,3,SUBJ_059520,Seated Lean Non Dom - FACE DOWN,Relaxes and moves hand to target location,Transition,Cheek - pinch skin,6.601562,...,-1.0,-1.0,-1.0,0,12,1,1,163.0,52,24.0
4,SEQ_000007_000004,NaN,SEQ_000007,4,SUBJ_059520,Seated Lean Non Dom - FACE DOWN,Relaxes and moves hand to target location,Transition,Cheek - pinch skin,5.566406,...,-1.0,-1.0,-1.0,0,12,1,1,163.0,52,24.0

In [ ]:
X = df_merged_train[feature_list].values  # assuming feature_list is your input columns
y = df_merged_train["sequence_type"].values

In [46]:
df_train = df_merged_train[feature_list_with_seq_id]

In [47]:
df_train.shape

(574945, 341)